#ifndef SRC_UTILITIES_GLOBALDEFINES_H_
#define SRC_UTILITIES_GLOBALDEFINES_H_

//#define TUNING_PIDS

//Drive Config
#define DRIVE_X_AXIS 0
#define DRIVE_Y_AXIS 1
#define DRIVE_AGITATE 8
#define DRIVE_SHIFT_LOW 7
#define DRIVE_SHIFT_HIGH 6
#define DRIVE_INTAKE_IN_BUTTON 2
#define DRIVE_INTAKE_OUT_BUTTON 3

//Gear Subsystem Buttons
/*//Unused
#define GEAR_SUBSYSTEM_ACTUATE_DOWN 1
#define GEAR_SUBSYSTEM_ACTUATE_UP 2
#define GEAR_SUBSYSTEM_CLOSE_CLAMP 3
#define GEAR_SUBSYSTEM_OPEN_CLAMP 4
*/
#define PICKUP_GEAR 5
#define PLACE_GEAR 6
#define DRIVER_PICKUP_GEAR 10
#define DRIVER_PLACE_GEAR 9
#define REHOME_GEAR 14 //buttonBox2

//Intake Buttons
#define INTAKE_IN_BUTTON 7
#define INTAKE_OUT_BUTTON 8
#define INTAKE_ACTUATE_OUT_BUTTON 9
#define INTAKE_ACTUATE_IN_BUTTON 10

//BallFeeder and Shooter Buttons - armJoystick
#define SHOOT_BUTTON 1
#define SHOOTER_OFF_BUTTON 7
#define ARM_INTAKE_IN_BUTTON 8
#define AGITATOR_REVERSE 9
#define VISION_HOLD_ON 10
#define VISION_SET_ON 11
#define VISION_SET_OFF 12

#define SPEED_UP 4
#define SPEED_DOWN 3
#define HOOD_UP 6
#define HOOD_DOWN 5

#define SHOOT_FROM_HOPPER 14
#define SHOOT_FROM_CENTER_GEAR 15
#define SHOOT_FROM_SIDE_GEAR 16
#define SHOOT_FROM_LOADING_ZONE 13
#define SHOOT_REMOVE_BALLS 1
#define SHOOT_FROM_LAUNCHPAD_LINE 3
#define SHOOT_SEARCH_AND_DESTROY 4


//Climber Buttons
#define UNLOCK_INTAKE_BUTTON 17
#define LOCK_INTAKE_BUTTON 17
#define CLIMB_BUTTON 9
#define TRIGGER_CLIMB_BUTTON 1

//Turret
//#define TURRET_UPPER_SOFT_STOP 3.7314814815 //Programming Bot
//#define TURRET_LOWER_SOFT_STOP -3.7314814815 //Programming Bot
#define TURRET_UPPER_SOFT_STOP 2.5
#define TURRET_LOWER_SOFT_STOP -5.5
#define MANUAL_CONTROL_AXIS 2
#define TURRET_JOYSTICK_DEADBAND 0.1
#define MANUAL_OVERRIDE_BUTTON 2
#define PREDICTIVE_SEEK_BUTTON 11
#define REHOME_TURRET 13 //buttonBox2

//Shooter
#define HOOD_UPPER_SOFT_STOP 1
#define HOOD_LOWER_SOFT_STOP 0

//Shooter
#define GEAR_UPPER_SOFT_STOP 0.175
#define GEAR_LOWER_SOFT_STOP -0.3

#endif /* SRC_UTILITIES_GLOBALDEFINES_H_ */
